FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/types/package*.json ./packages/types/
COPY apps/web-dashboard/package*.json ./apps/web-dashboard/

RUN npm install

COPY packages/types ./packages/types
COPY apps/web-dashboard ./apps/web-dashboard

WORKDIR /app/apps/web-dashboard
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/apps/web-dashboard/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
