FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/types/package*.json ./packages/types/
COPY services/api/package*.json ./services/api/

RUN npm install

COPY packages/types ./packages/types
COPY services/api ./services/api

WORKDIR /app/services/api
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=5000

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/packages/types ./packages/types
COPY --from=builder /app/services/api/package*.json ./services/api/
COPY --from=builder /app/services/api/dist ./services/api/dist
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app/services/api
EXPOSE 5000

CMD ["node", "dist/index.js"]
